In [1]:
import pandas as pd

# Creating a Series

In [2]:
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
s = pd.Series([10,20,30],index=['a','b','c'])
print(s)

a    10
b    20
c    30
dtype: int64

In [4]:
print(s['a'])
print(s[0])

10
10

# Creating the DataFrame

In [5]:
data = {
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'Salary':[50000,60000,70000]
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [6]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)

(3, 3)
Index(['Name', 'Age', 'Salary'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
Name      object
Age        int64
Salary     int64
dtype: object

# Selecting Columns

In [7]:
print(df['Name'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [10]:
print(df[['Name','Salary']])

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes
None

In [12]:
print(df.describe())

        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

In [13]:
print(df['Salary'].value_counts())

50000    1
60000    1
70000    1
Name: Salary, dtype: int64

In [14]:
print(df['Salary'].unique)

<bound method Series.unique of 0    50000
1    60000
2    70000
Name: Salary, dtype: int64>

In [15]:
print(df['Salary'].nunique())

3

# Indexing and Selection

In [16]:
print(df.loc[0])

Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object

In [17]:
print(df.loc[0,'Name'])

Alice

In [19]:
df.loc[0:2]

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [20]:
df.set_index('Name',inplace=True)
print(df)

         Age  Salary
Name
Alice     25   50000
Bob       30   60000
Charlie   35   70000

In [26]:
print(df.loc['Alice'])

Age          25
Salary    50000
Name: Alice, dtype: int64

In [27]:
print(df.iloc[0])

Age          25
Salary    50000
Name: Alice, dtype: int64

In [28]:
print(df.iloc[0,1])

50000

# Data Filtering

In [29]:
print(df[df['Age']>=30])

         Age  Salary
Name
Bob       30   60000
Charlie   35   70000

In [30]:
iris = pd.read_csv("iris.csv")
print(type(iris))

<class 'pandas.core.frame.DataFrame'>

In [32]:
df = iris.copy()
print(df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [33]:
df.head(6)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa

In [34]:
print(df.shape)
print(df.dtypes)

(150, 5)
sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [35]:
print(df.columns)

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [ ]:
# if we want to change the name of the columns then 
df.columns = [] # here we neeed to pass the same number of list size

In [37]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [38]:
print(df["sepal.length"])
# we can also access the column using df.sepallength

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [39]:
df.isnull()

     sepal.length  sepal.width  petal.length  petal.width  variety
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [40]:
df.isnull().sum()  # it sums how much entries are null in particular column

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [41]:
df.iloc[1:4,2:4]

   petal.length  petal.width
1           1.4          0.2
2           1.3          0.2
3           1.5          0.2

In [42]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [43]:
a = df.drop(0) # it removes the 0th row and create the new copy of it if we does not provide inplace=True
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [44]:
df.drop(0,inplace=True) # it removes the oth row and it removes using lebel and not index
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa

In [45]:
df.index

RangeIndex(start=1, stop=150, step=1)

In [46]:
df.index[0],df.index[3]

(1, 4)

In [47]:
df.drop(df.index[[0,1]],inplace = True)  # to remove the multiple rows using index
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa

In [48]:
df["sepal.length"]>5

3      False
4      False
5       True
6      False
7      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: sepal.length, Length: 147, dtype: bool

In [49]:
df[df["sepal.length"]>5]

     sepal.length  sepal.width  petal.length  petal.width    variety
5             5.4          3.9           1.7          0.4     Setosa
10            5.4          3.7           1.5          0.2     Setosa
14            5.8          4.0           1.2          0.2     Setosa
15            5.7          4.4           1.5          0.4     Setosa
16            5.4          3.9           1.3          0.4     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[117 rows x 5 columns]

In [50]:
df[df.variety == 'Setosa'].describe()

       sepal.length  sepal.width  petal.length  petal.width
count     47.000000    47.000000     47.000000    47.000000
mean       5.012766     3.440426      1.468085     0.248936
std        0.360324     0.384289      0.177061     0.108091
min        4.300000     2.300000      1.000000     0.100000
25%        4.800000     3.200000      1.400000     0.200000
50%        5.000000     3.400000      1.500000     0.200000
75%        5.200000     3.700000      1.600000     0.300000
max        5.800000     4.400000      1.900000     0.600000

In [51]:
df.reset_index(drop = True,inplace = True) 
df.index

RangeIndex(start=0, stop=147, step=1)

In [52]:
del df["sepal.width"]   #to delete the column

In [53]:
df

     sepal.length  petal.length  petal.width    variety
0             4.6           1.5          0.2     Setosa
1             5.0           1.4          0.2     Setosa
2             5.4           1.7          0.4     Setosa
3             4.6           1.4          0.3     Setosa
4             5.0           1.5          0.2     Setosa
..            ...           ...          ...        ...
142           6.7           5.2          2.3  Virginica
143           6.3           5.0          1.9  Virginica
144           6.5           5.2          2.0  Virginica
145           6.2           5.4          2.3  Virginica
146           5.9           5.1          1.8  Virginica

[147 rows x 4 columns]

In [54]:
df = iris.copy()
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [55]:
df["difference_pl_pw"] = df["petal.length"] -df["petal.width"]  #to add the new column
print(df)

     sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

     difference_pl_pw
0                 1.2
1                 1.2
2                 1.1
3                 1.3
4                 1.2
..                ...
145               2.9
146               3.1
147               3.2
148               3.1
149               3.3

[150 rows x 6 columns]

In [56]:
df.head()

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw
0,5.1,3.5,1.4,0.2,Setosa,1.2
1,4.9,3.0,1.4,0.2,Setosa,1.2
2,4.7,3.2,1.3,0.2,Setosa,1.1
3,4.6,3.1,1.5,0.2,Setosa,1.3
4,5.0,3.6,1.4,0.2,Setosa,1.2

In [57]:
df.iloc[2:4,1:3] = 0
df.head()

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw
0,5.1,3.5,1.4,0.2,Setosa,1.2
1,4.9,3.0,1.4,0.2,Setosa,1.2
2,4.7,0.0,0.0,0.2,Setosa,1.1
3,4.6,0.0,0.0,0.2,Setosa,1.3
4,5.0,3.6,1.4,0.2,Setosa,1.2

In [59]:
import numpy as np

In [60]:
df.iloc[2:4,1:3] = np.nan
df

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw
0,5.1,3.5,1.4,0.2,Setosa,1.2
1,4.9,3.0,1.4,0.2,Setosa,1.2
2,4.7,NaN,NaN,0.2,Setosa,1.1
3,4.6,NaN,NaN,0.2,Setosa,1.3
4,5.0,3.6,1.4,0.2,Setosa,1.2
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica,2.9
146,6.3,2.5,5.0,1.9,Virginica,3.1
147,6.5,3.0,5.2,2.0,Virginica,3.2
148,6.2,3.4,5.4,2.3,Virginica,3.1
149,5.9,3.0,5.1,1.8,Virginica,3.3

In [61]:
df.dropna(inplace = True)  # to remove the na entries and if we want to make changes inplace

In [62]:
df.head()
df.reset_index(drop = True,inplace = True)
df.head

<bound method NDFrame.head of      sepal.length  sepal.width  petal.length  petal.width    variety  \
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             5.0          3.6           1.4          0.2     Setosa
3             5.4          3.9           1.7          0.4     Setosa
4             4.6          3.4           1.4          0.3     Setosa
..            ...          ...           ...          ...        ...
143           6.7          3.0           5.2          2.3  Virginica
144           6.3          2.5           5.0          1.9  Virginica
145           6.5          3.0           5.2          2.0  Virginica
146           6.2          3.4           5.4          2.3  Virginica
147           5.9          3.0           5.1          1.8  Virginica

     difference_pl_pw
0                 1.2
1                 1.2
2                 1.2
3                 1.3
4                 1.1
..                ...
143               2.9
144               3.1
145               3.2
146               3.1
147               3.3

[148 rows x 6 columns]>

In [63]:
df.iloc[2:4,1:3] = np.nan
df

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw
0,5.1,3.5,1.4,0.2,Setosa,1.2
1,4.9,3.0,1.4,0.2,Setosa,1.2
2,5.0,NaN,NaN,0.2,Setosa,1.2
3,5.4,NaN,NaN,0.4,Setosa,1.3
4,4.6,3.4,1.4,0.3,Setosa,1.1
...,...,...,...,...,...,...
143,6.7,3.0,5.2,2.3,Virginica,2.9
144,6.3,2.5,5.0,1.9,Virginica,3.1
145,6.5,3.0,5.2,2.0,Virginica,3.2
146,6.2,3.4,5.4,2.3,Virginica,3.1
147,5.9,3.0,5.1,1.8,Virginica,3.3

In [64]:
df["sepal.width"].fillna(df["sepal.width"].mean(),inplace = True)
df["petal.length"].fillna(df["petal.length"].mean(),inplace = True)
df

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw
0,5.1,3.500000,1.400000,0.2,Setosa,1.2
1,4.9,3.000000,1.400000,0.2,Setosa,1.2
2,5.0,3.046575,3.820548,0.2,Setosa,1.2
3,5.4,3.046575,3.820548,0.4,Setosa,1.3
4,4.6,3.400000,1.400000,0.3,Setosa,1.1
...,...,...,...,...,...,...
143,6.7,3.000000,5.200000,2.3,Virginica,2.9
144,6.3,2.500000,5.000000,1.9,Virginica,3.1
145,6.5,3.000000,5.200000,2.0,Virginica,3.2
146,6.2,3.400000,5.400000,2.3,Virginica,3.1
147,5.9,3.000000,5.100000,1.8,Virginica,3.3

In [65]:
#strings based data
df["Gender"] = "Female"
df.iloc[0:10,6] = "Male"
df

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw,Gender
0,5.1,3.500000,1.400000,0.2,Setosa,1.2,Male
1,4.9,3.000000,1.400000,0.2,Setosa,1.2,Male
2,5.0,3.046575,3.820548,0.2,Setosa,1.2,Male
3,5.4,3.046575,3.820548,0.4,Setosa,1.3,Male
4,4.6,3.400000,1.400000,0.3,Setosa,1.1,Male
...,...,...,...,...,...,...,...
143,6.7,3.000000,5.200000,2.3,Virginica,2.9,Female
144,6.3,2.500000,5.000000,1.9,Virginica,3.1,Female
145,6.5,3.000000,5.200000,2.0,Virginica,3.2,Female
146,6.2,3.400000,5.400000,2.3,Virginica,3.1,Female
147,5.9,3.000000,5.100000,1.8,Virginica,3.3,Female

In [66]:
def f(s):
    if s == "Male":
        return 0
    else :
        return 1
    
df["sex"] = df.Gender.apply(f)
df

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw,Gender,sex
0,5.1,3.500000,1.400000,0.2,Setosa,1.2,Male,0
1,4.9,3.000000,1.400000,0.2,Setosa,1.2,Male,0
2,5.0,3.046575,3.820548,0.2,Setosa,1.2,Male,0
3,5.4,3.046575,3.820548,0.4,Setosa,1.3,Male,0
4,4.6,3.400000,1.400000,0.3,Setosa,1.1,Male,0
...,...,...,...,...,...,...,...,...
143,6.7,3.000000,5.200000,2.3,Virginica,2.9,Female,1
144,6.3,2.500000,5.000000,1.9,Virginica,3.1,Female,1
145,6.5,3.000000,5.200000,2.0,Virginica,3.2,Female,1
146,6.2,3.400000,5.400000,2.3,Virginica,3.1,Female,1
147,5.9,3.000000,5.100000,1.8,Virginica,3.3,Female,1

In [67]:
del df["Gender"]
df

,sepal.length,sepal.width,petal.length,petal.width,variety,difference_pl_pw,sex
0,5.1,3.500000,1.400000,0.2,Setosa,1.2,0
1,4.9,3.000000,1.400000,0.2,Setosa,1.2,0
2,5.0,3.046575,3.820548,0.2,Setosa,1.2,0
3,5.4,3.046575,3.820548,0.4,Setosa,1.3,0
4,4.6,3.400000,1.400000,0.3,Setosa,1.1,0
...,...,...,...,...,...,...,...
143,6.7,3.000000,5.200000,2.3,Virginica,2.9,1
144,6.3,2.500000,5.000000,1.9,Virginica,3.1,1
145,6.5,3.000000,5.200000,2.0,Virginica,3.2,1
146,6.2,3.400000,5.400000,2.3,Virginica,3.1,1
147,5.9,3.000000,5.100000,1.8,Virginica,3.3,1

In [76]:
ans = df.groupby(['sepal.length'])[['sepal.width','petal.length']].mean()
print(ans)

              sepal.width  petal.length
sepal.length
4.3              3.000000      1.100000
4.4              3.033333      1.333333
4.5              2.300000      1.300000
4.6              3.400000      1.266667
4.7              3.200000      1.600000
4.8              3.180000      1.580000
4.9              2.950000      2.266667
5.0              3.064658      2.082055
5.1              3.477778      1.722222
5.2              3.425000      2.075000
5.3              3.700000      1.500000
5.4              3.407763      2.386758
5.5              2.842857      3.228571
5.6              2.816667      4.200000
5.7              3.100000      3.587500
5.8              2.885714      4.071429
5.9              3.066667      4.700000
6.0              2.733333      4.650000
6.1              2.850000      4.750000
6.2              2.825000      4.750000
6.3              2.855556      5.133333
6.4              2.957143      5.157143
6.5              3.000000      5.240000
6.6              2.950000      4.500000
6.7              3.050000      5.262500
6.8              3.000000      5.400000
6.9              3.125000      5.275000
7.0              3.200000      4.700000
7.1              3.000000      5.900000
7.2              3.266667      5.966667
7.3              2.900000      6.300000
7.4              2.800000      6.100000
7.6              3.000000      6.600000
7.7              3.050000      6.600000
7.9              3.800000      6.400000